plugins {
    id 'java'
    id 'application'
    id 'idea'
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

repositories {
    mavenCentral()
    mavenLocal()
}

version = '1.0-SNAPSHOT'

dependencies {
    testImplementation 'org.testng:testng:7.9.0'
    implementation 'org.slf4j:slf4j-simple:1.7.36'
}

test {
    useTestNG()
}